import type { Metadata, Viewport } from "next";
import "./globals.css";
import NextAuthProvider from "../components/NextAuthProvider";
import Layout from '../components/Layout';
import RegisterServiceWorker from "../components/RegisterServiceWorker";
import { ThemeProvider } from "theme";
import { Raleway } from "next/font/google";
import AppSystemBarMimic from "components/AppSystemBarMimic";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["cyrillic", "latin", "latin-ext"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};
export const viewport: Viewport = {
  themeColor: "#1976d2",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
        <meta name="theme-color" content="#1976d2" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="HR Frontend" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/attendance192.png" sizes="192x192" />
        <link rel="apple-touch-icon" href="/icons/attendance192.png" />
      </head>
      <body className={`${raleway.variable}`}>
        <NextAuthProvider>
          <ThemeProvider options={{ key: "mui" }}>
            <Layout> {children}</Layout>
            <AppSystemBarMimic/>
          </ThemeProvider>
        </NextAuthProvider>
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
