import type { Metadata, Viewport } from "next";
import "./globals.css";
import NextAuthProvider from "../components/NextAuthProvider";
import Layout from '../components/Layout';
import RegisterServiceWorker from "../components/RegisterServiceWorker";
import { ThemeProvider } from "theme";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["cyrillic", "latin", "latin-ext"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};
export const viewport: Viewport = {
  themeColor: "#1976d2",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="manifest" href="/manifest.json"/>
        <link rel="icon" href="/icons/attendance192.png" sizes="192x192" />
      </head>
      <body className={`${raleway.variable}`}>
        <NextAuthProvider>
          <ThemeProvider options={{ key: "mui" }}>
         <Layout> {children}</Layout>
          </ThemeProvider>
        </NextAuthProvider>
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
